spring:
  datasource:
    url: jdbc:postgresql://10.1.1.30:5432/academia
    username: academia
    password: academia
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true




